### ISSUE TITLE
Provide custom logger API for custom plugin builds

### ISSUE THREAD

**Issue by luxixing** [redpanda-data/connect#1155]
In stream mode, can I replace service.Logger with my own implementation? Because in the case of stream mode, I want the logs to be output to my own logging service, such as tcp logger, instead of the standard output

**Comment by josephwoodward** [comment]
I've made a start on this here: https://github.com/benthosdev/benthos/pull/1883

**Comment by mihaitodor** [comment]
Fixed in [v4.23.0](https://github.com/redpanda-data/connect/releases/tag/v4.23.0).
