### ISSUE TITLE
GCP Credentials - Ability to set credentials as a json instead of just GOOGLE_APPLICATION_CREDENTIALS

### ISSUE THREAD

**Issue by pradeeppattamatta** [redpanda-data/connect#1761]
Hi,

Can we have the option to set the credentials as a json. We can inject that json value through base64 encoded environment variable (or through cli-flags+vault). This will help with auth for the Google Pubsub, BigQuery and cloud storage components. 

The go library provides the support for it using https://pkg.go.dev/google.golang.org/api/option#WithCredentialsJSON.

This is useful in my case where I cannot create the credentials json file in the container in a secure way.

If you think this is a good option, I can submit a PR. Thank you!

**Comment by Jeffail** [comment]
Hey! Sure that sounds generally useful.

**Comment by janiodev** [comment]
Hi, I want to add the option to create explicit credentials to this issue, like in AWS components.

**Comment by mihaitodor** [comment]
Fixed in #2759 and is available since [v4.33.0](https://github.com/redpanda-data/connect/releases/tag/v4.33.0).
