### ISSUE TITLE
Splunk HEC output - Add TLS client certificate/key settings

### ISSUE THREAD

**Issue by prigio** [redpanda-data/connect#1905]
The new splunk_hec output enforces TLS communication.  Would it be possible to add configs for TLS client certificate and key?

In some use cases, HEC-formatted data is sent to pre-processing systems which will use TLS client validation AND token authentication to authenticate and authorize requests.

Thank you

**Comment by Jeffail** [comment]
Hey @prigio, I believe we can and it should hopefully be straight forward. Will mark this as an enhancement as I'm not sure we'll get this done in time for the next release.

**Comment by mihaitodor** [comment]
Fixed in #2666.
