### ISSUE TITLE
Adding an `array` method to bloblang

### ISSUE THREAD

**Issue by gramian** [redpanda-data/connect#2545]
Dear All,

I would like to propose adding a method `array` to bloblang, which returns always an array. Specifically, every non-array input is returned as single element array, while an array input is returned as-is. This is similar to the `bytes` method and motivated originally by parsing XML files transformed to JSON: An XML element with a single child element (or attribute) is returned as sub-object, while multiple child elements/attributes are returned as array. To further process such a subtree, it needs to be ensured always an array is returned. Practically this results in unwieldy constructs like `this.with("name").values().flatten()`. The newly proposed `array` method would reduce this to the more readable `this.name.array()`.

Here is the associated pull request: https://github.com/benthosdev/benthos/pull/2538

Thank you for considering this enhancement

Best

**Comment by gramian** [comment]
@Jeffail WDYT? Does this addition fit? Is the PR in order?

**Comment by mihaitodor** [comment]
Fixed in Benthos [v4.31.0](https://github.com/redpanda-data/benthos/blob/main/CHANGELOG.md#4310---2024-07-10).
