### ISSUE TITLE
Exclude enterprise licensed plugins from the all package

### ISSUE THREAD

**Issue by sagikazarmark** [redpanda-data/connect#2627]
Currently there is no way to import all open source plugins. I'd argue that people who used the `public/all` package before may not be aware that some of the plugins now have a different license.

Would be nice to move those plugins out into an `enterprise` package.

**Comment by emaxerrno** [comment]
good idea.

**Comment by Jeffail** [comment]
Hey @sagikazarmark, good shout, I've started off by breaking out two new packages with explicit licensing, details here: https://github.com/redpanda-data/connect/issues/2621#issuecomment-2149134811

And the plugin example repo is updated to show how to build an entirely FOSS distribution: https://github.com/benthosdev/benthos-plugin-example
