### ISSUE TITLE
main.go seems to be Redpanda Enterprise licensed

### ISSUE THREAD

**Issue by jobegrabber** [redpanda-data/connect#2629]
`main.go` seemingly [imports](https://github.com/redpanda-data/connect/blob/82b7dd2f64508e7c657cc222145911db9c6d9bf4/cmd/redpanda-connect/main.go#L9) and [uses](https://github.com/redpanda-data/connect/blob/82b7dd2f64508e7c657cc222145911db9c6d9bf4/cmd/redpanda-connect/main.go#L21) code that is now proclaimed to be part of [`a Redpanda Enterprise file`](https://github.com/redpanda-data/connect/blob/82b7dd2f64508e7c657cc222145911db9c6d9bf4/internal/impl/kafka/topic_logger.go#L3).

Following [this README](https://github.com/redpanda-data/connect/blob/82b7dd2f64508e7c657cc222145911db9c6d9bf4/licenses/README.md) and reading the ["Redpanda Community License Agreement"](https://github.com/redpanda-data/connect/blob/82b7dd2f64508e7c657cc222145911db9c6d9bf4/licenses/rcl.md), this effectively means everyone invoking the `connect` binary invokes code licensed under it - which in turn would mean anyone not paying Redpanda Enterprise license fees is not allowed to run it.

**Comment by AndreasBergmeier6176** [comment]
See https://github.com/redpanda-data/connect/tree/main/public/bundle/free

**Comment by Jeffail** [comment]
Hey @jobegrabber, if you want to explicitly only import FOSS features then follow the updated plugin example repo: https://github.com/benthosdev/benthos-plugin-example
