### ISSUE TITLE
Dependency Licensing issue caused by couchbase/gocbcoreps

### ISSUE THREAD

**Issue by JeremyTheocharis** [redpanda-data/connect#2644]
Hi,

Jeremy from benthos-umh(https://github.com/united-manufacturing-hub/benthos-umh) here. In one of the new benthos versions you introduced the package "couchbase/gocbcoreps". However, that package has no license header or LICENSE file, which got flagged by our FOSSA instance.

Are you aware of this?

Regards,
Jeremy

**Comment by Jeffail** [comment]
Hey @JeremyTheocharis, it looks as though it's just a repo carved out for shared dependencies and they probably forgot to add it as both of the repos that bring it in on their organisation (https://github.com/couchbase/gocb and https://github.com/couchbase/gocbcore) are Apache 2.0. Unfortunately they do not have issues open on any of their repos, but if you are able to contact them I'm sure they'd be willing to add a quick fix.

**Comment by JeremyTheocharis** [comment]
I wrote them on Discord as well as created a PR. Let's see what happens

**Comment by JeremyTheocharis** [comment]
LICENSE file now exists, benthos should now be license error free (not legal advice)
