### ISSUE TITLE
public free bundle missing the xml package import

### ISSUE THREAD

**Issue by terryherron** [redpanda-data/connect#2651]
The free bundle is missing the xml package.  This has the xml processor along with parse_xml and format_xml bloblang functions.

https://github.com/redpanda-data/connect/tree/main/public/bundle/free

Excellent project Ashley and congrats on the sale.  -Terry (sas)

**Comment by Jeffail** [comment]
Hey @terryherron, the xml components should be getting pulled in via https://github.com/redpanda-data/connect/blob/main/public/bundle/free/package.go#L43, there's a few hops going on but it eventually ends up at https://github.com/redpanda-data/connect/blob/main/public/components/pure/extended/package.go#L22

Are you able to share what your project looks like?

**Comment by terryherron** [comment]
Legend @Jeffail .

I missed that pure/extended import.  All is well, thank you.
