### ISSUE TITLE
sql_insert - high CPU usage mainly due to GC cycles and allocations.

### ISSUE THREAD

**Issue by spanwp** [redpanda-data/connect#2668]
Hello. We are using the latest version of Red Panda Connect v4.30.1. 
We are using kafka_franz as input and sql_insert as output. 
With such a configuration:

```
input:
  kafka_franz:
    seed_brokers: ["kafka-1:9092"]
    topics: ["events"]
    regexp_topics: false
    consumer_group: "events"
    client_id: events
    auto_replay_nacks: true
    batching:
      count: 10000 # LARGE BATCH SIZE!
      byte_size: 0
      period: ""
      check: ""

pipeline:
  processors:
    - label: message_mapping
      mapping: |
        root = {
          "datetime": this.datetime,
          "eventType": this.adv.eventType,
          # ...

output:
  sql_insert:
    driver: "clickhouse"
    dsn: clickhouse://localhost:9000/wpartner?dial_timeout=200ms&max_execution_time=60
    table: wpartner_tech
    columns:
      [
        datetime,
        eventType,
        # ...
      ]
    args_mapping: |
      root = [
        this.datetime,
        this.eventType,
        # ...
      ]
    max_in_flight: 20
    batching:
      count: 0
      byte_size: 0
      period: ""
      check: ""
```

With these settings, we observe drastic CPU usage. It is mainly used on GC cycles and allocations.
The larger the batch size, the worse the application performs.
Pprof leads to these places in the code:
- https://github.com/redpanda-data/connect/blob/6d472c05d9d0c86f4a9ae27ad969e252f86618d5/internal/impl/sql/output_sql_insert.go#L239
- https://github.com/redpanda-data/benthos/blob/4edb4b29808fae57d97f166670e65248d02c1173/public/service/message.go#L473

It is very odd that in this place the entire slice is being allocated as many times as the batch size. (output_sql_insert.go#L239)

<img width="747" alt="obraz" src="https://github.com/redpanda-data/connect/assets/104571800/ca43aaa2-3759-492c-ae1c-81731b70fe28">

<img width="747" alt="obraz" src="https://github.com/redpanda-data/connect/assets/104571800/21e58324-1361-476c-9f09-5f7f8bbcd72d">

<img width="1432" alt="obraz" src="https://github.com/redpanda-data/connect/assets/104571800/dccb9061-86ed-4082-af9a-d8ca2a64a173">

<img width="1490" alt="obraz" src="https://github.com/redpanda-data/connect/assets/104571800/37fae9bb-104b-4650-b01d-b348d751a84b">

Is there any chance to optimize this code? Thanks.

**Comment by spanwp** [comment]
I implemented an ugly fix to see if it would improve the application’s performance. It definitely did.

<img width="1448" alt="obraz" src="https://github.com/redpanda-data/connect/assets/104571800/a2e1225b-0ced-41d1-8100-9dc5202d37dc">

<img width="714" alt="obraz" src="https://github.com/redpanda-data/connect/assets/104571800/3e59d2ac-c18b-4593-b861-022c1eecfadc">

<img width="762" alt="obraz" src="https://github.com/redpanda-data/connect/assets/104571800/8b1020d5-40ab-4ae5-b061-7b19eb8e2791">

My fix: 
<img width="1218" alt="obraz" src="https://github.com/redpanda-data/connect/assets/104571800/c8a9dc57-9563-4731-a11e-3f08fe3af690">

<img width="1557" alt="obraz" src="https://github.com/redpanda-data/connect/assets/104571800/b0fee6a5-c08d-49bb-aad6-69ad67cfecc6">

**Comment by Jeffail** [comment]
Hey @spanwp, thanks for the investigation. Ideally we don't want to expose internal structs in the public package. However, one thing we could consider is something like this:

```go
exec := batch.BloblangQueryFunc(s.argsMapping)
...
resMsg, err := exec(i)
```

This would reduce us down into one allocation regardless of batch size.

**Comment by spanwp** [comment]
@Jeffail To maintain communication continuity, I have copied my response from Slack below.
Great. Thank you so much for your response. I don’t know the program well enough to fix this "bug", but I can offer to test your fix.

**Comment by Jeffail** [comment]
Sorry, PR closed automatically but I'm keeping this open until the `connect` changes are merged.

**Comment by spanwp** [comment]
@Jeffail If I am right, this PR fixed the issue: https://github.com/redpanda-data/connect/pull/2693

**Comment by Jeffail** [comment]
Yep, thanks @spanwp,a  tagged release is hopefully coming out early this week.
