### ISSUE TITLE
Enhance the http_client output with additional error checking

### ISSUE THREAD

**Issue by brknstrngz** [redpanda-data/connect#2699]
Not all HTTP APIs are built equal. Some treat HTTP as just a transport layer and respond with a 200 code to nearly every request. In such cases they encode the actual error message in the HTTP response, which the caller then must parse and implement application logic around.

The current implementation of the http_client output assumes success on 200 and thus errors are not pushed back to the input. It would be great to be able to process the HTTP response body with a mapping processor, where we can test for actual success.

**Comment by mihaitodor** [comment]
Hey @brknstrngz 👋 In such cases, you can use the `http` processor as an output. This pattern is documented [here](https://docs.redpanda.com/redpanda-connect/components/processors/about/#using-processors-as-outputs).

Also, in some cases, you can configure [`drop_on`](https://docs.redpanda.com/redpanda-connect/components/outputs/http_client/#drop_on) and wrap this output in a [`fallback` output](https://docs.redpanda.com/redpanda-connect/components/outputs/fallback/) where you can read the [`fallback_error` metadata](https://v4.benthos.dev/docs/components/outputs/fallback#metadata). However, with this approach, I think it's not currently possible to access the actual response body.

**Comment by mihaitodor** [comment]
Salut! :) You're welcome!
