### ISSUE TITLE
Incorrect Usage: flag provided but not defined: -r when in streams mode

### ISSUE THREAD

**Issue by webfrank** [redpanda-data/connect#2701]
Hi,
  when starting Redpanda Connect in streams mode it Dows not accept "-r" flag to specify resources.

I'm running it from docker image (latest) with this args:

docker.redpanda.com/redpandadata/redpanda connect -r resources.yaml streams streams.yaml

and the error is

Incorrect Usage: flag provided but not defined: -r when in streams mode

**Comment by redben** [comment]
duplicate #2672

**Comment by Jeffail** [comment]
Yeah this is dupe, I've added an update to #2672
