### ISSUE TITLE
Bump bundled version to latest release (v4.47.0)

### ISSUE THREAD

**Issue by Scarjit** [redpanda-data/connect#2905]
Currently both [free](https://github.com/redpanda-data/connect/blob/main/public/bundle/free/go.mod) and [enterprise](https://github.com/redpanda-data/connect/blob/main/public/bundle/enterprise/go.mod) are on v4.31.0, requiring the use for `replace` when writing plugins that target the newer versions (https://github.com/united-manufacturing-hub/benthos-umh/pull/63/files).

**Comment by mihaitodor** [comment]
Hey @Scarjit, thank you for the reminder! I raised #2908 to address this issue.

**Comment by Jeffail** [comment]
Hey @Scarjit, if you remove the replace directive and run:

```
go get github.com/redpanda-data/connect/public/bundle/free/v4@latest
go get github.com/redpanda-data/connect/v4@latest
go get github.com/redpanda-data/benthos/v4@latest
```

What is the indirect version of `connect/v4` that gets pulled in? If I try that locally on a repository such as https://github.com/redpanda-data/redpanda-connect-plugin-example I get the latest `v4.37.0`, which is what I would expect (and it comes with the latest plugins). You can see the resulting changes here: https://github.com/redpanda-data/redpanda-connect-plugin-example/pull/26

The reason that we aren't actively tagging the packages within `public/bundle` is that the content doesn't change across releases, as the suite of imports they bring in (which is their ownly purpose) doesn't change. My understanding is that as long as you update the package that actually brings in the imports (`github.com/redpanda-data/connect/v4`) then you'll get the latest plugins and bug fixes from the connect repo.

**Comment by Scarjit** [comment]
Hi @Jeffail,

that indeed pulls in the latest dependencies :)
