### ISSUE TITLE
Documentation: missing tick in Bloblang Arithmetic page

### ISSUE THREAD

**Issue by ntx-ben** [redpanda-data/connect#3029]
There seems to be a missing tick under `Docs -> Connect -> Bloblang -> Bloblang Arithmetic`:

![image](https://github.com/user-attachments/assets/d3d892ff-214e-4208-988d-78d3cc78deac)

**Comment by mihaitodor** [comment]
Nice catch, thank you! I raised a PR for it here: https://github.com/redpanda-data/rp-connect-docs/pull/106.
