### ISSUE TITLE
pg_stream: UUIDs are not handled as strings when handling changes

### ISSUE THREAD

**Issue by ntx-ben** [redpanda-data/connect#3038]
I'm using the newly released `v1.41.0` version.

I'm trying the `pg_stream` input connector and am receiving an initial snapshot (`stream_snapshot: true`) of a particular table to pump data into kafka. My table contains various columns, the primary key being `machine_id` of type UUID. 

After making a change in a specific record in that table, I receive the updated record in redpanda-connect. However, I noticed that the primary key is now an array instead of a string (which is the native type for UUID in postgres I assume):

![image](https://github.com/user-attachments/assets/07f3cb0b-34ef-4ec2-9fd6-3e38977bc754)

How can I stream the same data structure consistently using `pg_stream` input connector? Thanks!

**Comment by mihaitodor** [comment]
Hey @ntx-ben 👋 I guess we're not doing anything special on our end (maybe @rockwotj has more details), but a quick workaround would be to use a `mapping` processor to fix it with some Bloblang code like this:

```coffee
root = this
root.machine_id = this.machine_id.map_each(i -> i.string()).join("")
```

I'm actually not sure what each number in that array represents or how to convert them into a proper UUID. If you can figure out what the algorithm is, please let me know.

**Comment by ntx-ben** [comment]
Thanks for the quick turn around!

**Comment by rockwotj** [comment]
This will be out in the next release as the fix has landed on main - thanks for the report and giving the output a spin!

**Comment by ntx-ben** [comment]
I tested with `main` and confirm the issue is fixed! JSONB is also handled very nicely now!

Thanks again for your swift support 👍
