### ISSUE TITLE
Kafka Output Timestamp

### ISSUE THREAD

**Issue by kozelok** [redpanda-data/connect#398]
Currently using Kafka output to send messages for later processing with Kafka topic configuration set to CreateTime. Is it possible to extend the Kafka output to use an interpolation function when setting Kafka message time? 

Ideally, this would be a metadata key to avoid looking into payload again.

**Comment by DpoBoceka** [comment]
Hey @kozelok, everything is possible. I am currently working on bringing the interpolation to all filed of  `json` processor, so I might have a look on `kafka` output as well, If @Jeffail is not opposed of that idea in general. 
Actually, if he's not, I would encourage you to take a look at the codebase and see if it is easy to add interpolation to desired field of `kafka` config

**Comment by Jeffail** [comment]
Hey @kozelok, it's possible. It would involve parsing an interpolated value into a timestamp, which potentially could lead to errors, so it wouldn't be a straight forward addition. We'd need to consider what behaviour to default to when the parsing fails (message gets dropped, timestamp not set, timestamp set to something else, etc).

I'm not totally clued into the `CreateTime` behaviour in Kafka so I'm not sure right now what should be a default there, and what alternative options we'd need to provide for error handling.

**Comment by kozelok** [comment]
@Jeffail 
Thank you for the quick response. To give some background, Kafka topics can either be configured to use a time in each message of "CreateTime"(Time the message was created by a producer) or "LogAppendTime", (Time it was received by Kafka). 

For interpolation, I was thinking we could default to the current implementation, which is letting sarama set the time.

**Comment by mihaitodor** [comment]
Implemented via #2665.
